/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;
import Clases.Persona;
import com.db4o.Db4o;
import com.db4o.ObjectContainer;
import com.db4o.ObjectSet;
import javax.swing.JOptionPane;

/**
 *
 * @author LENOVO
 */
public class Eliminar_Usuario extends javax.swing.JFrame {

    /**
     * Creates new form Eliminar_Usuario
     */
    public Eliminar_Usuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        eliminar = new javax.swing.JButton();
        Buscar = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel1.setText("SELECCIONE UN CAMPO PARA BUSCAR UN USUARIO");

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel2.setText("CEDULA DE USUARIO A ELIMINAR");

        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel3.setText("FILTRO");

        jLabel4.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel4.setText("CEDULA");

        eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS/eliminar.png"))); // NOI18N
        eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarActionPerformed(evt);
            }
        });

        Buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS/lupa_1.png"))); // NOI18N
        Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarActionPerformed(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS/deshacer.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione un campo:", "Ver todos", "Cedula" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jTable1.setForeground(new java.awt.Color(204, 204, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Cedula", "Primer_nom", "secundo_nom", "Primer_Ape", "Segundo_Ape", "Calle_principal", "Calle_Secundaria", "Sexo", "Edad"
            }
        ));
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setHeaderValue("Cedula");
            jTable1.getColumnModel().getColumn(1).setHeaderValue("Primer_nom");
            jTable1.getColumnModel().getColumn(2).setHeaderValue("secundo_nom");
            jTable1.getColumnModel().getColumn(3).setHeaderValue("Primer_Ape");
            jTable1.getColumnModel().getColumn(4).setHeaderValue("Segundo_Ape");
            jTable1.getColumnModel().getColumn(5).setHeaderValue("Calle_principal");
            jTable1.getColumnModel().getColumn(6).setHeaderValue("Calle_Secundaria");
            jTable1.getColumnModel().getColumn(7).setHeaderValue("Sexo");
            jTable1.getColumnModel().getColumn(8).setHeaderValue("Edad");
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(132, 132, 132)
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(164, 164, 164)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(eliminar)
                        .addGap(141, 141, 141))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 925, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton3)))
                .addGap(23, 23, 23)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel3)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(eliminar))
                .addGap(25, 25, 25)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
                                                                                          
        if (jComboBox1.getSelectedIndex() == 0) {
            //deshabilitarParametros();
        } else {
            if (jComboBox1.getSelectedIndex() == 1) {
               // deshabilitarParametros();
            } else {
                if (jComboBox1.getSelectedIndex() == 2) {
                   // deshabilitarParametros();
                } else {
                    if (jComboBox1.getSelectedIndex() == 3) {
                       // habilitarParametros();
                    }
                }
            }
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarActionPerformed
        
     // ObjectContainer BaseD = Db4o.openFile(Inicio.direccionBD);
       // Buscar_UsuarioCedula(BaseD);
        // Cerrar_BD(BaseD);
    }//GEN-LAST:event_BuscarActionPerformed

    private void eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarActionPerformed
     //  ObjectContainer BaseD = Db4o.openFile(Inicio.direccionBD);
     //   Eliminar_UsuarioCedula(BaseD);
     //   Cerrar_BD(BaseD);
    }//GEN-LAST:event_eliminarActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
         this.dispose();
            Pag_adm vsar1 = new Pag_adm ();
            vsar1.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    private void Buscar_UsuarioCedula(ObjectContainer BaseD) {
        if (jComboBox1.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(null, "Selección invalida");

        } else {
            if (jComboBox1.getSelectedIndex() == 1) {

                Persona Ebuscar = new Persona(null,null, null, null, null, null, null, null , 0);

                ObjectSet result = BaseD.get(Ebuscar);
                MostrarDatos(result);
            } else {
                if (jComboBox1.getSelectedIndex() == 2) {

                    String cedulaAux = JOptionPane.showInputDialog("Ingrese la cedula a consultar");

                    Persona Ebuscar = new Persona(null, null, null, null, null, null, null , null, 0);

                    ObjectSet result = BaseD.get(Ebuscar);
                    MostrarDatos(result);

                } else {
                    if (jComboBox1.getSelectedIndex() == 3) {
//                        habilitarParametros();
                       // BuscarParametros(basep);

                    }
                }
            }
        }
     //Borrar la eleccion y ponerla al inicio
        jComboBox1.setSelectedIndex(0);
    }
    
    public void MostrarDatos(ObjectSet result) {
        String matrizUsuario[][] = new String[result.size()][7];
        int matrizUsuario1[][] = new int [result.size()][8];

        if (result.size() == 0) {
            JOptionPane.showMessageDialog(null, "ElUsuario no se encuentra en la base de datos");
        } else {
            for (int i = 0; i < result.size(); i++) {

                Persona miE = new Persona();

                miE = (Persona) result.get(i);
                matrizUsuario[i][0]= miE.getCedula();
                matrizUsuario[i][1] = miE.getPrimer_nom();
                matrizUsuario[i][2]= miE.getSegundo_Nom();
                matrizUsuario[i][3]= miE.getPrimer_Ape();
                matrizUsuario[i][4] = miE.getSegundo_Ape();
                matrizUsuario[i][5]= miE.getCalle_principal();
                matrizUsuario[i][6]=miE.getCalle_Secundaria();
                matrizUsuario[i][7]= miE.getSexo();
                matrizUsuario1[i][8]= miE.getEdad();
                

                jTable1.setModel(new javax.swing.table.DefaultTableModel(matrizUsuario, new String[]{"Cedula","Primer_nom" ,"Segundo_Nom","Primer_Ape","Segundo_Ape","Calle_principal","Calle_Secundaria" ," Sexo","Edad"}));

            }
        }

    }
    

    private void Eliminar_UsuarioCedula(ObjectContainer BaseD) {
       Registro_UsuarioN Einterfaz = new Registro_UsuarioN();//Crear un objeto de la clase Estudiantes para traer el metodo Comprobar_Estudiantes

        if (jTextField1.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Codigo no valido");
        } else {

            String Cedula = jTextField1.getText();
            Persona Leliminar = new Persona(Cedula, null, null, null, null, null, null , null, 0);
            ObjectSet result = BaseD.get(Leliminar);

            if (Einterfaz.Comprobar_Usuario(BaseD, Cedula) == 0) {

                JOptionPane.showMessageDialog(null, "El Usaurio no existe en la base de datos");

            } else {
                Persona Estudianteeliminar = (Persona) result.next();

                BaseD.delete(Estudianteeliminar);
                JOptionPane.showMessageDialog(null, "El Usuario fue eliminado de la base de datos exitosamente");
            }

        }

        //Borrar el campo de texto
        jTextField1.setText("");
    }
    private void Cerrar_BD(ObjectContainer BaseD) {
         BaseD.close();
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Buscar;
    private javax.swing.JButton eliminar;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
    
}
