/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

/**
 *
 * @author EDU
 */
public class Eliminar_representante extends javax.swing.JFrame {

    /**
     * Creates new form Eliminar_representante
     */
    public Eliminar_representante() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        cedula_repre = new javax.swing.JTextField();
        eliminar_usu = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        buscar_usu = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(74, 127, 203));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("CONSULTA REPRESENTANTE");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 390, 30));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS/deshacer.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 80));

        jPanel3.setBackground(new java.awt.Color(165, 210, 240));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Ingrese la cedula del representante que desea buscar:");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, 30));

        cedula_repre.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        cedula_repre.setForeground(new java.awt.Color(0, 0, 0));
        cedula_repre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cedula_repreActionPerformed(evt);
            }
        });
        cedula_repre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cedula_repreKeyTyped(evt);
            }
        });
        jPanel3.add(cedula_repre, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 60, 150, 40));

        eliminar_usu.setBackground(new java.awt.Color(153, 204, 255));
        eliminar_usu.setForeground(new java.awt.Color(102, 102, 102));
        eliminar_usu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS/eliminar.png"))); // NOI18N
        eliminar_usu.setBorder(null);
        eliminar_usu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminar_usuActionPerformed(evt);
            }
        });
        jPanel3.add(eliminar_usu, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 60, 50, 40));

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Ingrese la cedula del representante a eliminar:");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 36, -1, 20));

        jComboBox1.setBackground(new java.awt.Color(102, 102, 102));
        jComboBox1.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jComboBox1.setForeground(new java.awt.Color(0, 0, 0));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una opcion:", "Ver todos", "Cedula", " " }));
        jComboBox1.setBorder(null);
        jPanel3.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 160, 40));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Cedula", "Primer Nombre", "Segundo Nombre", "Primer Apellido", "Segundo Apellido", "Sexo", "Edad", "Telefono", "Correo Electronico", "Calle Principal", "Calle Secundaria"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setPreferredSize(new java.awt.Dimension(75, 64));
        jScrollPane1.setViewportView(jTable1);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 700, 160));

        buscar_usu.setBackground(new java.awt.Color(153, 204, 255));
        buscar_usu.setForeground(new java.awt.Color(102, 102, 102));
        buscar_usu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS/lupa.png"))); // NOI18N
        buscar_usu.setBorder(null);
        buscar_usu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscar_usuActionPerformed(evt);
            }
        });
        jPanel3.add(buscar_usu, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, 50, 40));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 730, 270));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 732, 10));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cedula_repreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cedula_repreActionPerformed
        boolean resultado;

        // TODO add your handling code here:
    }//GEN-LAST:event_cedula_repreActionPerformed

    private void cedula_repreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cedula_repreKeyTyped
        char aux = evt.getKeyChar();
        boolean numeros = aux >= 48 && aux <= 57;
        if (numeros == false) {
            System.out.println("Ingrese solo numeros" + evt.getKeyChar());
            evt.consume();
        }
    }//GEN-LAST:event_cedula_repreKeyTyped

    private void eliminar_usuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminar_usuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eliminar_usuActionPerformed

    private void buscar_usuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscar_usuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buscar_usuActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.dispose();
        Pag_adm vsar1 = new Pag_adm ();
        vsar1.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buscar_usu;
    private javax.swing.JTextField cedula_repre;
    private javax.swing.JButton eliminar_usu;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
